### ISSUE TITLE
内部ストレージ保存後のデータ確認方法

### ISSUE THREAD

**Issue by yagichan160** [yagichan160/recyclerview_prc#19]
保存されたかの確認方法はありますでしょうか？
保存ファイルの読み込み処理を実装すればわかりそうですが、、お手軽な方法がもしあればご教授頂きたいです。

※端末の画面選択ウィンドウで、ルート名→ファイル #内のデータに保存されているかどうかでしょうか？

**Comment by friegen** [comment]
同じ場所にあるかわからないんですが、右下の方にある`Device File Explorer`ってのを開いて、data/dataの下にある自分のパッケージを探すと内部ストレージに保存していれば画像が見れます。


https://gyazo.com/9c0254bae1185afb226d470637692cf8

**Comment by yagichan160** [comment]
Device File Explorer
こちらありました！data/dataの下の自分のパッケージもあったと思います。
run as...のような記載があり見えなかったような気がしますが、、、
記憶があいまいなので、今日改めて確認してみます。

**Comment by yagichan160** [comment]
コード見直しを行い、Device File Explorerを確認したところ保存されてました！
この確認方法で良いのですよね？

![innnerstrage cache_save](https://user-images.githubusercontent.com/60102416/75728458-32792b00-5d2b-11ea-9f81-7e27e0990747.png)

**Comment by friegen** [comment]
あってます！
ただこの方法だと新しい画像を保存しても端末の抜き差しをしないと反映されないとかあったりするので、注意が必要だったりします。

あとはコマンドプロンプトからadbコマンドからshellに入って確認できたりします。

![無題](https://user-images.githubusercontent.com/5162745/75736067-960d5380-5d3f-11ea-9068-cb940ba091f4.png)

**Comment by yagichan160** [comment]
ご確認有難うございます！
>ただこの方法だと新しい画像を保存しても端末の抜き差しをしないと反映されないとかあったりするので、注意が必要だったりします。
こちら昨日遭遇しました。。
デバイス・ファイル・エクスプローラー下の端末を選択するプルダウン部分で端末を選択しなおすと更新がかかるようで保存後の画像が確認できました！（抜き差し無しでもいけました）

コマンドプロンプトでの確認方法も試してみます！

解決したのでIssueはCloseします！有難うございました！
