### ISSUE TITLE
スクロール最下部のlist削除後の画面表示がスクロール最上部へ移動してしまう問題

### ISSUE THREAD

**Issue by yagichan160** [yagichan160/recyclerview_prc#20]
main画面上、スクロール最下部のlistを削除(左右スワイプ)すると、
画面表示がスクロール最上部に戻ってしまう現象がおきてます。

削除後の、画面表示をスクロール最下部(もしくは削除したlistの周辺)が表示されるようにしたいと考えているのですが、これは、、こういうものなのでしょうか？

※現象をmp4ファイルにしてます。Chatworkへ添付致しますので、ご確認頂きたく。。

**Comment by friegen** [comment]
ぱっと見、処理は間違っていなさそうです、、、。
なんでだろう。。。

**Comment by friegen** [comment]
これ試してみてください。
https://qiita.com/fu_neko/items/77683a800a9da9ca29d1

AndroidStudio3.6向けのビルド設定に変更されててプロジェクトがビルドできない(´・ω・｀)

**Comment by friegen** [comment]
StackOverFlow先生も同じこと言ってるので、まずはお試しを。。。
https://stackoverflow.com/questions/28189371/using-notifyitemremoved-or-notifydatasetchanged-with-recyclerview-in-android

**Comment by friegen** [comment]
あと
https://github.com/yagichan160/recyclerview_prc/blob/master/app/src/main/java/com/example/myapplication/adapter/RecyclerAdapter.kt#L48-L49
の呼び出す順番を変えてみるとか。たまにこういう簡単なので意図した動きになったりします。

**Comment by yagichan160** [comment]
ご確認有難うございます。
https://github.com/yagichan160/recyclerview_prc/issues/20#issuecomment-594976736
まずはこちら試してみます。
Qiitaみてみました！removeの通知はしたけど、それは削除されたlistにのみで他のlistにも削除されたこと(表示位置が変わること)を通知する必要があるのよ。ってことですね。試してみます。。

あと、こちらも合わせて試してみます。（前後させるだけで変わったりするんですね。。奥が深い）
https://github.com/yagichan160/recyclerview_prc/issues/20#issuecomment-594979425

**Comment by yagichan160** [comment]
週末、ご助言頂いた2点試してみました！
削除時のダイアログ表示を追加し、削除しないを選択した際の挙動としては、
こちらを実装することでlistの再生成が行われ意図した動作をしてくれました。
ただ、削除実行後はやはり、LiveDataが動いて削除前後ではなく、dbデータのid若い順から順にlistが生成される現象が起きています。

Twitterでおっしゃってた、「adapterの生成箇所の変更」は、
以下のviewadapter初期化処理以降をobserve{}外に出すということでしょうか？

（observeされた、allMemoDataを以下observe{}の外で確認できれば実現できそうなのですが、、、。仕様的にできなさそう気がしてます。。）


```readAllMemoData.observe(this@MainActivity, Observer {allMemoData->
                viewAdapter =
                    RecyclerAdapter(this@MainActivity, this@MainActivity,allMemoData.toMutableList())
                viewManager =
                    LinearLayoutManager(this@MainActivity, LinearLayoutManager.VERTICAL, false)
                recyclerView = findViewById<RecyclerView>(R.id.mainRecyclerView).apply {
                    setHasFixedSize(true)

                    layoutManager = viewManager
                    adapter = viewAdapter
                }
                itemTouchHelper = ItemTouchHelper(getRecyclerViewSimpleCallBack())
                itemTouchHelper.attachToRecyclerView(recyclerView)
            })

        }
```

**Comment by friegen** [comment]
端的に言えば、LiveDataで通知されたデータを使って1からAdapterを生成しなおしているので1番上にスクロールしているように見えています。

新たに生成されたAdapter的には

「1から作成されたんだけど？前にいたAdapterのこと知らないしスクロール位置は一番上っしょ！」

となっています。

なので、どちらかの対応になるかと思います。

1. Adapterを再生成しないようにして、Adapter内のデータ更新を行う
→全量差分だと思うのでDiffUtil使って差分取るのが良いのかな？って思います。
　多分それで良い感じにアニメーションしてくれそうです。

2.そもそもDBの読み込みにLiveDataを使うのをやめる
→削除/更新時にLiveDataがテーブルの変更を検知して良い感じにLiveDataにデータを詰め込んで通知してくれています。
　今はこれがある意味邪魔です。
　なのでLiveDataを使わないようにする選択肢も1つです。


個人的には2推しです。
LiveDataで変更通知を受け取るのは便利ですけど、ユースケースに合わなくて実装が複雑になるくらいだったら最初から使わないっていう作戦です。

**Comment by yagichan160** [comment]
有難うございます。
２については一応やってみたのですが、、、力不足でできませんでした。
個人的にも２を進めたいです。

まず１について
　adapterの再生成をしないようにする。というのは、
　条件分岐で最初(はじめてアプリを立ち上げる時)以外はadapterの生成を行わないようにする
　ということでしょうか？
　条件分岐だとすると、「最初の読み込み以外」を示す条件が思いつきませんでした。
　（頭が固いだけかもしれません、、、）
　DiffUtilについては、こちらを参考に自前adapterに実装してみました。
　[https://qiita.com/nakker1218/items/271760a2cfa90e41fb4e]

　削除や更新を行った後に呼び出せば良いのかなと思ってますが、、。
　毎回adapterが生成される部分を改善できず使い方が正しいのかまではわかっておりません。

２について
　こちらは、アプリ内で実装してる他のLiveDataの実装(以前サンプルコードで頂いた、Success、Failedの状態キャッチする実装)と同じようにやろうとしたのですが、
　RecyclerAdapterの初期化に必要な引数（型List<Memodata>） をどう持ってこれば良いか
　わかりませんでした。。

　具体的には、
　以下のようなコードをMainViewModel.ktに作成したのですが、
　これだと欲しい型が得られないのかなと。
（これだと返り値を設定できず。コルーチン処理の仕様だと思いますが）

　```   fun read() {　

        viewModelScope.launch(Dispatchers.Default) {
            runCatching {
                database.memoDao().read()　//←ここをreadメソッドへ変更した

            }.fold(

                onSuccess = {
                    createViewState.postValue(CreateMemoState.Success)
                },
                onFailure = {
                    createViewState.postValue(CreateMemoState.Failed)
                }

            )
        }
    }
```

**Comment by friegen** [comment]
>　条件分岐で最初(はじめてアプリを立ち上げる時)以外はadapterの生成を行わないようにする
　ということでしょうか？
　条件分岐だとすると、「最初の読み込み以外」を示す条件が思いつきませんでした。

lateInitにしてますが、一旦こいつをnullableにして、nullかどうかで判断してはどうでしょうか？
https://github.com/yagichan160/recyclerview_prc/blob/master/app/src/main/java/com/example/myapplication/activity/MainActivity.kt#L27

ベストはRecyclerViewからAdapterを取得して、Adapterが設定されているかどうかで判断です。


> ２について

`database.memoDao().read()　`←こいつの中身がわからないのですが、単純にこれじゃだめですか？

```
    @Query("select * from MemoData")
    fun getAll(): LiveData<List<MemoData>>

↓↓↓↓↓↓↓↓

    @Query("select * from MemoData")
    fun getAll(): List<MemoData>
```

で、getAllで取得したデータをLiveDataで通知してあげるです。
そうすればテーブルの中身が変わってもobserveが勝手にされることはないはずです。

**Comment by yagichan160** [comment]
１について
`lateInitにしてますが、一旦こいつをnullableにして、nullかどうかで判断してはどうでしょうか？`

これは、、、思いつきませんでした。確かにこれでできそうな気がします。
前：private lateinit var viewAdapter: RecyclerAdapter
後：private var viewAdapter : RecyclerAdapter? = null

にして、if(viewAdapter==null)の場合のみviewAdapterを初期化するとすれば良さそうですね！
あ、、でもこれだと、以下の内容にマッチしてませんかね？

`ベストはRecyclerViewからAdapterを取得して、Adapterが設定されているかどうかで判断です。`

２について
CWで記載した通りでございますm(__)m
https://www.chatwork.com/#!rid174510237-1288753159908401152

**Comment by friegen** [comment]
> あ、、でもこれだと、以下の内容にマッチしてませんかね？
ベストはRecyclerViewからAdapterを取得して、Adapterが設定されているかどうかで判断です。

マッチしてませんねｗ

CWにも回答しておきました。
https://www.chatwork.com/#!rid174510237-1288755197312499712

**Comment by yagichan160** [comment]
`マッチしてませんねｗ`
ですよね。。
ここは、、、おそらくデータの削除処理でlistのpositionを取得したのと同じようなことだと思うので、ググったりして試してみます！

`CWにも回答しておきました。`

確認します！

**Comment by friegen** [comment]
> ここは、、、おそらくデータの削除処理でlistのpositionを取得したのと同じようなことだと思うので、ググったりして試してみます！

多分、なにか勘違いしているような気がするのですが、recyclerViewからgetAdapterでadapterを取得するのです。
KotlinだとrecyclerView.adpterとかで取得できます。

**Comment by yagichan160** [comment]
勘違いというか、、よくわかっていませんでした。。
こんな感じで取得できるんですね。。
　int totalCount = recyclerView.getAdapter().getItemCount(); //合計のアイテム数
　int childCount = recyclerView.getChildCount(); // RecyclerViewに表示されてるアイテム数

公式Pageにもあったのでうまくできなかったら確認してみます！
公式Page：https://developer.android.com/reference/android/support/v7/widget/RecyclerView#getadapter

**Comment by friegen** [comment]
いや、アイテムの個数ではなく、、、。
まずは初回かどうかの判定なのでadapterがあるかないかの判定を、、、。

**Comment by yagichan160** [comment]
(´・ω・｀)
　recyclerView.adpter == null
で良いってことでしょうか・・・？

recyclerView が　findViewById<RecyclerView>(R.id.mainRecyclerView)だから、
この中にadapterがあるかどうか！

**Comment by friegen** [comment]
> 　recyclerView.adpter == null
で良いってことでしょうか・・・？

OKです！

**Comment by yagichan160** [comment]
> 2.そもそもDBの読み込みにLiveDataを使うのをやめる

こちら、CWのやりとり等参考に実装したところ、
以下ができました。
・データ読み込みはアプリ立ち上げ時のみ
・list削除時の挙動が意図通り（削除箇所にフォーカスさえている）

ただ、「listの更新、新規作成」ができていません。
実装のイメージがあっているか、ご確認頂けますでしょうか？


▼listの新規作成
MainActivity.ktで新規作成ボタンタップ
↓
CreateMemo.ktでMemoData作成及びDB書き込み、MemoDataをMainActivityへ渡す
↓
MainActivity.kt側でRecyclerViewの更新（MemoDataのinsert）

の流れになるかと思ってます。RecyclerViewの更新は、あくまでMainActivity.kt側でやるイメージなのですが、イメージ有ってますでしょうか？
また、この時指定するlistの挿入位置ってなにを指定すれば良さそうでしょうか？
（PrimaryKeyのuid?、list<MemoData>を読み込んでIndexofを取得し、それをpositionに設定?）

▼listの更新
MainActivity.ktで更新対象listをタップ
↓
CreateMemo.ktでMemoDataの変更及びDB更新、MemoDataをMainActivityへ渡す
↓
MainActivity.kt側でRecyclerViewの更新（MemoDataの更新）


と流れは新規作成と同じだと思ってます。ただ、この時指定するlistの挿入位置は新規作成と異なると思うのですが、、、なにを指定すれば良さそうでしょうか？（PrimaryKeyのuid？）

**Comment by friegen** [comment]
> CreateMemo.ktでMemoData作成及びDB書き込み、MemoDataをMainActivityへ渡す
↓
MainActivity.kt側でRecyclerViewの更新（MemoDataのinsert）

ここが矛盾してます。
DBへのInsertはあくまでCreateMemoでやって良いと思います。

> RecyclerViewの更新は、あくまでMainActivity.kt側でやるイメージなのですが、イメージ有ってますでしょうか？
また、この時指定するlistの挿入位置ってなにを指定すれば良さそうでしょうか？
（PrimaryKeyのuid?、listを読み込んでIndexofを取得し、それをpositionに設定?）

MainActivityでRecyclerViewの更新をするのはあってます。
Adapterにupdateメソッドでも生やして、Adapterが持っているListの中でUidが一致しているものがあれば、そのItemを更新。なければListにaddすれば良いかなと思います。
その際notifyItemChanged(的な名前のやつ)でViewの更新するのも忘れずに。

**Comment by yagichan160** [comment]
> ここが矛盾してます。
> DBへのInsertはあくまでCreateMemoでやって良いと思います。

あ、、、了解です。CreateMemo.kt側でDBへのinsertは行います。

> MainActivityでRecyclerViewの更新をするのはあってます。
> Adapterにupdateメソッドでも生やして、Adapterが持っているListの中でUidが一致しているものがあれば、そのItemを更新。なければListにaddすれば良いかなと思います。
> その際notifyItemChanged(的な名前のやつ)でViewの更新するのも忘れずに。

RecyclerViewの更新は、
CreateMemoからMainActivyへ渡されたMemoDataを渡す。
それを使って、、
RecyclerAdapter.ktにこんなメソッドをはやして更新か新規作成かを判定し、
RecyclerViewを更新。
であってますでしょうか・・・？

▼MemoDataの渡し方

```
CreateMemo.kt 側
//MemoData生成後、以下の通りMainActivityへ渡す
 val intent = intent.putExtra("test",memoData)
                setResult(Activity.RESULT_OK,intent)
```

```
MainActivity.kt側
//override fun onActivityResult()内で、以下の通り受け取る　
val memo = data?.getSerializableExtra("test") as? MemoData

//RecyclerAdapter(viewAdapter)のupdateメソッド読み出し。引数に受け取ったmemoDataを使用。
viewAdapter.update(memo,memo.uid)

```

▼updateメソッドイメージ

```
RecyclerAdapter.kt 

fun update(memo:MemoData,position: Int){　　　//←引数positionはMemoDataのuid?

　　//ここで新規か、更新かを判定する処理を入れる。
       //　if(itemList.position == position)で良いのかな…
　　//更新なら①と③を実施。新規なら②と③を実施するイメージ。。
 　  
　　 notifyItemInserted(position)　//①
        itemList.add(memo)　//②
        notifyItemRangeChanged(position,itemCount)　//③

    }
```

**Comment by friegen** [comment]
概ねあってますが、ちょっと間違っています。
削除のことを考えるとUid＝Positionとはならないです。
比較するのはあくまでUid同士です。

**Comment by yagichan160** [comment]
> //　if(itemList.position == position)で良いのかな…

ここが違うということでしょうか・・・？
if(itemList.uid == memo.uid)
ですかね？

これは、update()ないで削除もまとめてやってしまおうということですかね？
削除する際のpositionは、RecyclerViewのadapterPositionになるため、
position＝uidに必ずしもならない。

ということでしょうか・・・？

**Comment by friegen** [comment]
> if(itemList.uid == memo.uid)

多く括りで言えばあってますが、itemList自体にはuidを持っていないはずなので、どうやるかは検討してみてください。

> これは、update()ないで削除もまとめてやってしまおうという理解であってますでしょうか？

削除はRemove内でやってあげてください。
Uidは現状の作りだとDBのレコード番号になるはずなので、例えば、、、

1
2
3
4

とデータが有った場合で3を削除すると

1
2
4

になります。
Adapterのposition=2の時、4のデータが取れるってことです。

**Comment by yagichan160** [comment]
> 多く括りで言えばあってますが、itemList自体にはuidを持っていないはずなので、どうやるかは検討してみてください。

検討してみます。itemListの型がList<MemoData>なんでそこからMemoDataを抽出してやる必要がありそうですね。言葉で書くと、itemList内のいくつかのMemoDataの中で同じuidがあるかどうか？を条件分岐するイメージ。。。
itemList.get**でMemoData抽出できそう、、、かな？ググってみます。


> Adapterのposition=2の時、4のデータが取れるってことです。

更新と削除は分けるけど、(削除はRemove内でやるけど)
削除されるとpositionがずれるから更新時も意識しないっと！ってことですかね。。
デバッグで規則性みたいなのを見つけてFBかけながらコード完成させていきます。。。

**Comment by friegen** [comment]
> itemList.get**でMemoData抽出できそう、、、かな？ググってみます。

やり方は色々あると思いますが、Kotlinは便利なメソッドが生えてたりするので探してみてください。

> 更新と削除は分けるけど、(削除はRemove内でやるけど)
削除されるとpositionがずれるから更新時も意識しないと！ってことですかね。。
デバッグで規則性みたいなのを見つけてFBかけながらコード完成させていきます。。。

positionで比較している感じがしたのですが、、、。
> if(itemList.position == position)

ここのitemList.positionのpositionってUidを指してましたか？
ここまで書いておいて何なんですが、、、。

追加/更新/削除用のメソッドを用意するという手もあります。
やり方は人それぞれだったりするので、やりやすいやり方を模索してみてください。

**Comment by yagichan160** [comment]
> やり方は色々あると思いますが、Kotlinは便利なメソッドが生えてたりするので探してみてください。
ざっと見た感じ、フィルター等いろいろあるみたいなんで、どれが良いか試してみます！

> ここのitemList.positionのpositionってUidを指してましたか？
> ここまで書いておいて何なんですが、、、。

Uidだと思ってました、、あれ、違うものですかね？
ここのpositionはListのメソッドの1つ、、でしょうか？

**Comment by friegen** [comment]
>ここのpositionはListのメソッドの1つ、、でしょうか？ 

Listにはpositionっていうメソッドはありませんね。
https://github.com/yagichan160/recyclerview_prc/issues/20#issuecomment-596876987

上記に書いてあったコードです。

**Comment by yagichan160** [comment]
`fun update(memo:MemoData,position: Int){　　　//←引数positionはMemoDataのuid?
`
ここのpositionは、MemoDataのuidを想定してます。
CreateMemo.ktから受け取ったMemoDataをつかって、
MainActivity.ktで、RecyclerAdapter内のupdateメソッドをこんな感じで呼ぶつもりでした。　

`viewAdapter.update(MemoData,MemoData.uid)`

**Comment by friegen** [comment]
その説明では納得ですがコード上、`position`となっているので、誤解を生みます。
単純にuidを渡されているので変数名はuidで良いです。

uidという名前とpositionという名前では意味が全く違います。

**Comment by yagichan160** [comment]
これを、、
`fun update(memo:MemoData,position: Int)`

こんな感に、、
`fun update(memo:MemoData,uid: Int)`

に変更しますm(__)m
紛らわしいし誤解を生みますね。気を付けます。

ちなみにpositionは、RecyclerView内のListの位置を意味すると思ってますが、、認識あってますでしょうか？

**Comment by friegen** [comment]
> fun update(memo:MemoData,uid: Int)

そもそもなんですが、memoがuidを持っているので、個別でuidを引数で受け取る必要はないかなと思います。

> positionは、RecyclerView内のListの位置を意味すると思ってますが、、認識あってますでしょうか？

あってます！

**Comment by yagichan160** [comment]
> そもそもなんですが、memoがuidを持っているので、個別でuidを引数で受け取る必要はないかなと思います。

以下コードの①、③にInt型の変数を入れる必要があるようで
渡せるInt型がMemoData.uidくらいしか思いつかなかったため個別で渡そうと思った次第です。。
・・・渡さなくても成立しますでしょうか？

```
RecyclerAdapter.kt 

fun update(memo:MemoData,position: Int){　　　//←引数positionはMemoDataのuid?

　　//ここで新規か、更新かを判定する処理を入れる。
       //　if(itemList.position == position)で良いのかな…
　　//更新なら①と③を実施。新規なら②と③を実施するイメージ。。
 　  
　　 notifyItemInserted(position)　//①
        itemList.add(memo)　//②
        notifyItemRangeChanged(position,itemCount)　//③

    }

```

> あってます！

了解です！良かったです(;´Д｀)

**Comment by friegen** [comment]
以下で良いのでは無いでしょうか？
```
　　 notifyItemInserted(memo.uid)　//①
        itemList.add(memo)　//②
        notifyItemRangeChanged(memo.uid,itemCount)　//③
```

**Comment by friegen** [comment]
あ、、、。そもそなんですけど、`notifyItemInserted`と`notifyItemRangeChanged`はAdapterの持ち物なのでuidを渡してはだめです。
Positionを渡してください。

**Comment by yagichan160** [comment]
> あ、、、。そもそなんですけど、notifyItemInsertedとnotifyItemRangeChangedはAdapterの持ち物なのでuidを渡してはだめです。
> Positionを渡してください。

ダメなんですね(;´Д｀)
positionは、、MainActivityのonItemClick()で取得するのかなと思ってますが、
あってますでしょうか？

…あってたとして、、intent.putExtra()で複数のデータを渡せるんですかね？

（あ、でもCreateMemoへ渡してもCreateMemoだとposition使わないと思うんでここで渡すのも微妙のような、、でもCreateMemoだとposition取得できないような）

```
MainActivity.kt

override fun onItemClick(MemoData: MemoData, position: Int) {

        //Toast.makeText(this, "position $position was tapped", Toast.LENGTH_SHORT).show()
        val intent = Intent(this, CreateMemo::class.java)

        intent.putExtra("memoData", MemoData)
        startActivityForResult(intent, REQUEST_CODE)

    }

```

**Comment by friegen** [comment]
> positionは、、MainActivityのonItemClick()で取得するのかなと思ってますが、

あってます。

> intent.putExtra()で複数のデータを渡せるんですかね？

複数渡せますし、複数戻せます。

> CreateMemoだとposition使わないと思うんでここで渡すのも微妙のような、、

個人的にありっちゃありな気もします。
DialogFragmentとかに更新用のデータをそのまま渡して、基本的に使わずにそのまま呼び出し元に戻すっていうことはよくやったりします。

ただ、多分このままだと新規のときにposition無いじゃん！ってなると思うので、position渡しはやらずにAdapterのlistからpostionを取得する方法が良いと思ってます。

https://github.com/yagichan160/recyclerview_prc/issues/20#issuecomment-596869595
> MainActivityでRecyclerViewの更新をするのはあってます。
Adapterにupdateメソッドでも生やして、Adapterが持っているListの中でUidが一致しているものがあれば、そのItemを更新。なければListにaddすれば良いかなと思います。
その際notifyItemChanged(的な名前のやつ)でViewの更新するのも忘れずに。

一致したPostionを取っておけばよいです。

**Comment by yagichan160** [comment]
有難うございます。
Activity側はいまのままでよくて、(MemoDataの受け渡しを行うのと、それをAdapterのメソッドの引数に使用する)
Adapterのメソッドを作りこむイメージですね。
Adapterの実装についてはCWを参考にさせて頂きますm(__)m

**Comment by yagichan160** [comment]
ほぼほぼできたと思うのですが、
本Issueに対し、2点ほど最後(おそらく)に相談させてください。


①端末画面に上の表示でlistが埋め尽くされている状態(8つくらい）で、
メモデータの新規作成を行うと、新規listが表示されません。スクロールすると表示されます。
→新規メモデータの更新後、DB上の全メモデータの再読み込みを行う記述にすると本現象が解消され、スクロール無しでlistが表示されますが、、、他に回避手段有りますでしょうか？

```
MainActivity.kt（新規作成時の更新処理）
 val memo = data?.getSerializableExtra("test") as? MemoData
                if (memo != null) {
                    if (memo.uid == 0) {
                        progressBar.visibility = ProgressBar.VISIBLE
                        viewmodel.read()　　　　　　　　　　　　　//↓の前後どちらかでDB上のメモデータ再読み込みを行わないとlistが表示されない
                        viewAdapter.insert(memo)　　　　　　　　　//ここで新規メモデータの更新処理を行っている。
                        progressBar.visibility = ProgressBar.INVISIBLE
                }　//else以降省略...
```

```
RecyclerAdaptor.kt（メモデータ新規作成時のAdapter内での処理）
fun insert(memo: MemoData){
        if(itemList.isEmpty()){
            itemList.add(0,memo)
        }else{
            itemList.add(0,memo)　　　　　　　　　//0番目にメモデータ追加
            notifyItemInserted(0)　　　　　　　　　//画面への更新処理
            notifyItemRangeChanged(0,itemCount)　//↑
        }
    }
```

②listの削除を行っている最中に別の処理(新規作成やアプリたち下げとか)を行うと
次にメモデータの全読み込みを行った際に削除しきれなかったlistが再表示されます。

→これは、、保存中は他の処理ができないよう画面をロックする。などユーザーの動きを制限する処置を行うのが一般的でしょうか？

**Comment by friegen** [comment]
①
新規追加したタイミングでスクロール位置を一番上にずらしてみては？
> DB上の全メモデータの再読み込みを行う記述にすると本現象が解消され

これはAdapterを再生成しているからですね。
ReyclerViewにスクロール位置を動かすメソッドがあった気がします。

②
> 保存中は他の処理ができないよう画面をロックする。などユーザーの動きを制限する処置を行うのが一般的でしょうか？

一般的、、、かどうかはわかりませんが、画面ロックはよくやります。
通信中とかで他の画面に遷移されると困ったりするケースが結構あるので。
ロックを行うかどうかは仕様次第な気もします。

**Comment by yagichan160** [comment]
①
> 新規追加したタイミングでスクロール位置を一番上にずらしてみては？
> ReyclerViewにスクロール位置を動かすメソッドがあった気がします。

RecylerViewにそんなメソッドが、、。
Adapterの再生成でも目的は達成できそうですが、、わざわざ今回省いた項目なので、
RecyclerViewのメソッド使って一番上にずらしてみようと思います。。

②

> 一般的、、、かどうかはわかりませんが、画面ロックはよくやります。
> 通信中とかで他の画面に遷移されると困ったりするケースが結構あるので。
> ロックを行うかどうかは仕様次第な気もします。

なるほどです。
今回、データの更新処理が中断されると困ったことになる（削除したはずが削除されていない、メモ更新したのに更新されていない等）ので、処理中は戻るボタンや新規作成ボタンをロックしちゃおうと思います。

今回、LiveData(DB更新)をobserveした際に、「メモを保存しました」などのToastを表示するようにしてますが、この表示＝処理完了　というわけではないのですね。。。

**Comment by tsutomu-dobashi** [comment]
> 今回、LiveData(DB更新)をobserveした際に、「メモを保存しました」などのToastを表示するようにしてますが、この表示＝処理完了　というわけではないのですね。。。

処理完了したときに通知するべきだと思います。

**Comment by friegen** [comment]
> 今回、LiveData(DB更新)をobserveした際に、「メモを保存しました」などのToastを表示するようにしてますが、この表示＝処理完了　というわけではないのですね。。。

処理完了したときに通知するべきだと思います。

**Comment by yagichan160** [comment]
> 処理完了したときに通知するべきだと思います。

おっしゃる通りです。。勘違いしてました。。。
Adapterのメソッドで、Successが返ってきたら「メモを保存しました。」
Failedが返ってきたら「メモ保存に失敗しました。」

とToastを表示するようになっているので、Toastが出てきた時点で処理は完了してそうです。
Toastが表示される前に処理が中断されると困ったことになるので、、表示されるまではバックキーや画面操作を無効にするよう修正します。


```
RecyclerAdaptor.kt

（削除メソッド）
fun delete(data: Int) {

        viewModelScope.launch(Dispatchers.Default) {
            runCatching {
                database.memoDao().delete(data)　//判定対象の処理
            }.fold(

                onSuccess = {
                    createViewState.postValue(CreateMemoState.Success)　//DBの削除処理が成功したら、CreateMemoStateのSuccess処理を返す
                },
                onFailure = {
                    createViewState.postValue(CreateMemoState.Failed)　//DBの削除処理で異常が発生したら、CreateMemoStateのFailed処理を返す
                }

            )
        }
    }
```

```
MainActivity.kt（observe処理）

viewmodel.apply {
                    mainState.observe(this@MainActivity, Observer {
                        when (it) {
                            CreateMemoState.Success -> {
                                Toast.makeText(this@MainActivity, "メモを削除します", Toast.LENGTH_SHORT).show()
                                progressBar.visibility = ProgressBar.INVISIBLE

                            }
                            CreateMemoState.Failed -> {
                                Toast.makeText(this@MainActivity, "メモの削除に失敗しました", Toast.LENGTH_SHORT).show()
                            }
                        }
```
